services:
  evently.api:
    container_name: Evently.Api
    image: ${DOCKER_REGISTRY-}eventlyapi
    build:
      context: .
      dockerfile: src/Api/Evently.Api/Dockerfile
    ports:
      - 5000:8080
      - 5001:8081

  evently.database:
    container_name: Evently.Database
    image: postgres:16
    environment:
      - POSTGRES_DB=evently
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - 5432:5432

